zip_path = "<path to your .mbxc file>"
filter_labels = [
  "Markiert",
  "Chat",
  "Spam",
  "Abrechnungen nach Kategorie",
  "Wichtig",
  "Ge√∂ffnet",
  "Ungelesen",
  "Archiviert"
]
special_labels = [
  "Spam",
  "Papierkorb",
  "Gesendet"
]
